/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiProcessingRouteImport } from './routes/ai-processing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsNewRouteImport } from './routes/reports.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProcessingRoute = AiProcessingRouteImport.update({
  id: '/ai-processing',
  path: '/ai-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-processing': typeof AiProcessingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-processing': typeof AiProcessingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/incidents': typeof IncidentsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-processing': typeof AiProcessingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-processing'
    | '/dashboard'
    | '/login'
    | '/incidents/$id'
    | '/reports/new'
    | '/incidents/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-processing'
    | '/dashboard'
    | '/login'
    | '/incidents/$id'
    | '/reports/new'
    | '/incidents'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/ai-processing'
    | '/dashboard'
    | '/login'
    | '/incidents/$id'
    | '/reports/new'
    | '/incidents/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiProcessingRoute: typeof AiProcessingRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  ReportsNewRoute: typeof ReportsNewRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-processing': {
      id: '/ai-processing'
      path: '/ai-processing'
      fullPath: '/ai-processing'
      preLoaderRoute: typeof AiProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiProcessingRoute: AiProcessingRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  ReportsNewRoute: ReportsNewRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
